import { IMPERATIVE, TENSES } from '../../domain/conjugation.ts';
import { ENTRY_TYPES, LANGS, type EntryType, type Lang } from '../../domain/languages.ts';
import { entryContentSchema, type EntryContent } from '../../domain/schemas.ts';

export type EditableType = EntryType;
export const EDITABLE_TYPES: readonly EditableType[] = ENTRY_TYPES;

/**
 * One translation being edited. Flat on purpose: switching the entry type keeps
 * what was typed. `text` holds the word or the infinitive.
 */
export interface TranslationDraft {
  key: string;
  text: string;
  // Verbs (FR / ES / IT)
  reflexive: boolean;
  auxiliary: string;
  /** Six-person tenses, by conjugation schema key (present, passatoProssimo…). */
  tenses: Partial<Record<string, string[]>>;
  /** Imperative 2sg, 1pl, 2pl. */
  imperativeAffirmative: string[];
  imperativeNegative: string[];
  // Verbs (EN). The base form is the infinitive (`text`).
  pastSimple: string;
  pastParticiple: string;
  irregular: boolean;
}

export interface EntryDraft {
  type: EditableType;
  translations: Record<Lang, TranslationDraft[]>;
}

/** Field-level errors, keyed by `lang` or `lang.index.field` (ex. "it.0.conjugation.auxiliary"). */
export type DraftErrors = Partial<Record<string, ErrorCode>>;
export type ErrorCode = 'required' | 'auxiliary' | 'missingLanguage';

let nextKey = 0;
const newKey = () => `t${String(++nextKey)}`;

export function emptyTranslation(text = ''): TranslationDraft {
  return {
    key: newKey(),
    text,
    reflexive: false,
    auxiliary: '',
    tenses: {},
    imperativeAffirmative: [],
    imperativeNegative: [],
    pastSimple: '',
    pastParticiple: '',
    irregular: false,
  };
}

/** `count` cells, padded with empty strings. */
export function cells(values: readonly string[] | undefined, count: number): string[] {
  return Array.from({ length: count }, (_, i) => values?.[i] ?? '');
}

export function emptyDraft(
  options: { type?: EditableType; lang?: Lang; text?: string } = {},
): EntryDraft {
  const translations = {} as Record<Lang, TranslationDraft[]>;
  for (const lang of LANGS) {
    translations[lang] = [emptyTranslation(lang === options.lang ? (options.text ?? '') : '')];
  }
  return { type: options.type ?? 'word', translations };
}

/** Draft of an existing entry, or of content generated by the AI. */
export function draftFromContent(entry: EntryContent): EntryDraft {
  const translations = {} as Record<Lang, TranslationDraft[]>;
  for (const lang of LANGS) {
    translations[lang] = (entry.translations[lang] as readonly Record<string, unknown>[]).map(
      (t) => {
        const draft = emptyTranslation();
        const str = (key: string) => (typeof t[key] === 'string' ? t[key] : '');
        draft.text = str('text');
        draft.reflexive = t['reflexive'] === true;
        if (typeof t['conjugation'] === 'object' && t['conjugation'] !== null) {
          Object.assign(draft, conjugationDraft(lang, t['conjugation'] as Record<string, unknown>));
        }
        return draft;
      },
    );
  }
  return { type: entry.type, translations };
}

function conjugationDraft(lang: Lang, conjugation: Record<string, unknown>) {
  const strings = (value: unknown) =>
    Array.isArray(value) ? value.filter((v): v is string => typeof v === 'string') : [];
  if (lang === 'en') {
    return {
      pastSimple: typeof conjugation['pastSimple'] === 'string' ? conjugation['pastSimple'] : '',
      pastParticiple:
        typeof conjugation['pastParticiple'] === 'string' ? conjugation['pastParticiple'] : '',
      irregular: conjugation['irregular'] === true,
    };
  }
  const tenses: Partial<Record<string, string[]>> = {};
  for (const tense of TENSES[lang]) tenses[tense.key] = strings(conjugation[tense.key]);
  const imperative = (conjugation[IMPERATIVE[lang].key] ?? {}) as Record<string, unknown>;
  return {
    auxiliary: typeof conjugation['auxiliary'] === 'string' ? conjugation['auxiliary'] : '',
    tenses,
    imperativeAffirmative: strings(imperative['affirmative']),
    imperativeNegative: strings(imperative['negative']),
  };
}

const isEnglish = (lang: Lang) => lang === 'en';

/** The fields that matter for a type and language (others are kept but ignored). */
function relevantValues(t: TranslationDraft, type: EditableType, lang: Lang): string[] {
  switch (type) {
    case 'word':
      return [t.text];
    case 'verb':
      if (isEnglish(lang)) return [t.text, t.pastSimple, t.pastParticiple];
      return [
        t.text,
        t.auxiliary,
        ...TENSES[lang].flatMap((tense) => cells(t.tenses[tense.key], 6)),
        ...t.imperativeAffirmative,
        ...t.imperativeNegative,
      ];
  }
}

function isBlank(t: TranslationDraft, type: EditableType, lang: Lang): boolean {
  return relevantValues(t, type, lang).every((value) => value.trim() === '');
}

/** Content shape for one translation, before validation. */
function translationContent(t: TranslationDraft, type: EditableType, lang: Lang) {
  switch (type) {
    case 'word':
      return { text: t.text };
    case 'verb':
      return verbContent(t, lang);
  }
}

function verbContent(t: TranslationDraft, lang: Lang) {
  if (isEnglish(lang)) {
    return {
      text: t.text,
      conjugation: {
        base: t.text,
        pastSimple: t.pastSimple,
        pastParticiple: t.pastParticiple,
        irregular: t.irregular,
      },
    };
  }
  const conjugation: Record<string, unknown> = {};
  if (lang !== 'es') conjugation['auxiliary'] = t.auxiliary || undefined;
  for (const tense of TENSES[lang]) conjugation[tense.key] = cells(t.tenses[tense.key], 6);
  conjugation[IMPERATIVE[lang].key] = {
    affirmative: cells(t.imperativeAffirmative, 3),
    negative: cells(t.imperativeNegative, 3),
  };
  return { text: t.text, ...(t.reflexive ? { reflexive: true } : {}), conjugation };
}

/** Rows kept per language (blank rows are dropped), with their index in the draft. */
function keptRows(draft: EntryDraft, lang: Lang) {
  return draft.translations[lang]
    .map((t, index) => ({ t, index }))
    .filter(({ t }) => !isBlank(t, draft.type, lang));
}

function toRawContent(draft: EntryDraft) {
  const translations: Record<string, unknown[]> = {};
  for (const lang of LANGS) {
    translations[lang] = keptRows(draft, lang).map(({ t }) =>
      translationContent(t, draft.type, lang),
    );
  }
  return { type: draft.type, translations };
}

/** Stable representation of what the draft would save: used to detect unsaved changes. */
export function draftSignature(draft: EntryDraft): string {
  return JSON.stringify(toRawContent(draft));
}

export type DraftValidation =
  { ok: true; content: EntryContent } | { ok: false; errors: DraftErrors };

/** Validates with the shared Zod schema and maps its issues to form fields. */
export function validateDraft(draft: EntryDraft): DraftValidation {
  const result = entryContentSchema.safeParse(toRawContent(draft));
  if (result.success) return { ok: true, content: result.data };

  const errors: DraftErrors = {};
  for (const issue of result.error.issues) {
    const [, lang, row, ...rest] = issue.path;
    if (typeof lang !== 'string' || !(LANGS as readonly string[]).includes(lang)) continue;
    if (row === undefined) {
      errors[lang] = 'missingLanguage';
      continue;
    }
    const draftIndex = keptRows(draft, lang as Lang)[Number(row)]?.index;
    if (draftIndex === undefined) continue;
    const draftField = toDraftField(rest.map(String).join('.'));
    const code: ErrorCode = draftField === 'conjugation.auxiliary' ? 'auxiliary' : 'required';
    errors[`${lang}.${String(draftIndex)}.${draftField}`] ??= code;
  }
  return { ok: false, errors };
}

/**
 * Draft field name of a schema path (after the translation index): the English
 * base form is edited in the main field.
 */
function toDraftField(path: string): string {
  if (path === '' || path === 'conjugation.base') return 'text';
  return path;
}
